
// Generated by https://quicktype.io

import { PropertyButtonProps } from "../components/PropertyButton";
import { PropertyCardProps } from "../components/PropertyCard";
import { PropertyDescriptionProps } from "../components/PropertyDescription";
import { PropertyImageProps } from "../components/PropertyImage";
import { PropertyTitleProps } from "../components/PropertyTitle";

export interface Propertie {
  _id:         string;
  agregadoFav: boolean;
  descripcion: string;
  imagen:      string;
  nombre:      string;
}

export interface ChildrenProps{
  children:JSX.Element|JSX.Element[];
}

export interface PropContextProps{
  data:Propertie;
}

//Por si queremos agregar elementos a los componentes hijos
export interface PropertyCardHOCProps{
  ({data, children}:PropertyCardProps):JSX.Element;
  Title:(Props:PropertyTitleProps)=>JSX.Element;
  Image:(Props:PropertyImageProps)=>JSX.Element;
  Description?:(Props:PropertyDescriptionProps)=>JSX.Element;
  Button?:(Props:PropertyButtonProps)=>JSX.Element;
}