
// Generated by https://quicktype.io

export interface Propertie {
  _id:         string;
  agregadoFav: boolean;
  descripcion: string;
  imagen:      string;
  nombre:      string;
}

export interface ChildrenProps{
  children:JSX.Element|JSX.Element[];
}